#!/bin/bash

set -e

# This script uses mingw and the GNU tool chain for cross-compiling under
# linux. You can change the variables to not cross-compile for running
# with MSYS on windows. Whichever you choose, you need to provide the
# following as described and review the commands.

# static libs: libiconv, libintl, winpthread, libenet
# shared libs: sdl2, openal, curl

# libenet is not currently provided as a package in mingw distributions.
# The thing to check is that if pkgconfig is used, the one generated by
# libenet's make install does not have the proper libs for windows.
# Check that -lws2_32 and -lwinmm are libs in libenet.pc, as pkgconfig files
# are preferred by the configure script.

# Finally, you will need TeXLive to build the manual.

DESTINATION_DIRECTORY="$(pwd)/dist/windows/amd64"
HOST=x86_64-w64-mingw32
HOST_OPT=--host=$HOST
STRIP=${HOST}-strip

# A hack because configure doesn't automatically find Boost configuration for
# x86_64-w64-mingw32.
BOOST_PATH="/usr/${HOST}"
BOOST_OPTION="--with-boost=${BOOST_PATH}"

./configure --disable-silent-rules $HOST_OPT ${BOOST_OPTION}
make -j6 pkgdatadir="" localedir=locale
make install DESTDIR="${DESTINATION_DIRECTORY}" bindir=/ docdir=/ pkgdatadir=/ localedir=/locale
$STRIP "${DESTINATION_DIRECTORY}/7k-ambition.exe"

cd doc
latexmk
cd ..
cp doc/main.pdf "${DESTINATION_DIRECTORY}/7kaa-manual.pdf"

# Still need to add music and dlls
# then run NSIS on install.nsi
